cluster_label: null
input_genes: null
train_genes_names: null
val_genes_names: null
lambda_count: 1
lambda_ct_islands: 0
lambda_d: 1
lambda_f_reg: 1.0e-05
lambda_g1: 1
lambda_g2: 0
lambda_geary: 0
lambda_getis_ord: 0
lambda_l1: 0
lambda_l2: 0
lambda_moran: 0
lambda_neighborhood_g1: 0
lambda_r: 0
lambda_sparsity_g1: 0
learning_rate: 0.1
mode: filter
num_epochs: 200
random_state: 123
target_count: 100
