cluster_label: 'class_label'
lambda_count: 1
lambda_ct_islands: 1
lambda_d: 1
lambda_f_reg: 1.0e-05
lambda_g1: 1
lambda_g2: 1
lambda_geary: 1
lambda_getis_ord: 1
lambda_l1: 1
lambda_l2: 1
lambda_moran: 1
lambda_neighborhood_g1: 1
lambda_r: 1
lambda_sparsity_g1: 1
learning_rate: 0.1
filter: False
num_epochs: 1000
random_state: 123
target_count: 100
