cluster_label: null
input_genes: null
train_genes_names: null
val_genes_names: null
lambda_count: 1
lambda_ct_islands: 0
lambda_d: 1
lambda_f_reg: 1.0e-05
lambda_g1: 1
lambda_g2: 1
lambda_geary: 1
lambda_getis_ord: 1
lambda_l1: 1
lambda_l2: 1
lambda_moran: 1
lambda_neighborhood_g1: 1
lambda_r: 1
lambda_sparsity_g1: 1
learning_rate: 0.1
filter: True
num_epochs: 200
random_state: 123
target_count: 100
