cluster_label: 'Allen.class_label'
lambda_count: 1.0e-03
lambda_ct_islands: 1
lambda_d: 1.0e-3
lambda_f_reg: 1.0e-05
lambda_g1: 1
lambda_g2: 1
lambda_geary: 1
lambda_getis_ord: 1
lambda_l1: 1.0e-15
lambda_l2: 1.0e-18
lambda_moran: 1
lambda_neighborhood_g1: 1
lambda_r: 1.0e-09
lambda_sparsity_g1: 1
learning_rate: 0.1
filter: False
num_epochs: 1000
random_state: 42
target_count: None
